### ISSUE TITLE
Database schema 

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/notifications#5]
@h1alexbel let's discuss here

**Comment by l3r8yJ** [comment]
@h1alexbel I think it should just be one to many from user to token, wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ also, I think it will be handy, I'd we can associate token with alias, like `<token>` has alias `work`

Thus, user can simply toggle aliases to get notifications from different tokens

WDYT?

**Comment by h1alexbel** [comment]
I also think that the `notifications` system is not related to storing all of this stuff in the database

@l3r8yJ Or I miss something?

**Comment by l3r8yJ** [comment]
@h1alexbel good suggestion about alias

I was thinking notification the closest service to the github api and it would manage the database, do you have any thoughts on that?

**Comment by h1alexbel** [comment]
@l3r8yJ we can store data in notifications, but what about hub?

**Comment by h1alexbel** [comment]
@l3r8yJ I think, as we denote hub as a dispatcher of notifications, this system should be responsible for storing and mapping users and tokens in the database 

WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel hmm, yeah, that makes sense

**Comment by h1alexbel** [comment]
@l3r8yJ let's make transition to https://github.com/Blamer-io/hub/issues/24
